# This file contains RL-specific hyperparameters for PPO training

# seeds for reproducibility
seed: 42
eval_seed: 1000

n_envs: 32  # number of parallel environments for training
total_timesteps: 120000000  # 120 million timesteps
n_steps: 4096  # Number of steps per rollout per environment
start_learning_rate: 0.0003 # initial learning rate
end_learning_rate: 0.0001 # final learning rate, with linear decay
act_func_neg_slope: 0.2 # actor, critic LeakyReLU negative slope
